### ISSUE TITLE
submitted_by module cannot be enabled and has no effect on displayed author and date information

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/submitted_by#1]
With Backdrop 1.4.3 installed, I believe that the Token module is now in core; therefore I haven't separately installed it on my site. However, the Submitted By module can't tell that it's there, so I see "Requires: Token (missing)" in the Modules list and can't enable it.

Not sure what can be done to make the Submitted By module recognize the core version of Token!

**Comment by jackaponte** [comment]
A few more observations:
- Removing the dependency on the Token module from submitted_by.info allows me to enable the module; I can also use the token browser to find and insert tokens into the various Submitted By fields on a content type.
- However, my changes have no effect and only the default submitted by information appears, even after configuring content types.

This seems to indicate that a) the Token module dependency can be removed from the module, since it's already in core, but b) the module isn't actually working, at least not for this version of Backdrop!

**Comment by jackaponte** [comment]
Just checked on this with Backdrop 1.4.4; still can't enable the module without editing submitted_by.info to remove the token dependency, and still see no effect after enabling the module and changing submitted_by settings for content types.

**Comment by jackaponte** [comment]
I found the problem here, beginning from line 192 of `submitted_by.module`:

```
/**
 * Implements hook_process_node().
 *
 * Use hook_process_node() rather than hook_preprocess_node() as themes might
 * override the submitted variable unconditionally.
 */
function submitted_by_process_node(&$variables) {
  $node = $variables['elements']['#node'];
  $view_mode = $variables['view_mode'];
```

There is no `hook_process_node` in Backdrop, only `hook_preprocess_node`. Using the latter allows the module to actually work as designed, though there are obviously repercussions as noted in the comments of the Drupal module's code.

**Comment by herbdool** [comment]
@BWPanda are you still actively maintaining this module?

**Comment by ghost** [comment]
@herbdool No, sorry. Happy to hand it over to someone else if anyone's willing...?

**Comment by herbdool** [comment]
I'm not sure if I will or not, but I think we can safely accept the PR for this issue, so I'll do that at least.

**Comment by jackaponte** [comment]
Sweet, thanks @herbdool!
